### ISSUE TITLE
케이크 정보 열람시 모달창 여러번 나타나는 버그

### ISSUE THREAD

**Issue by lazarus0320** [patisiel-study/decorate-my-cake-frontend#30]
## 어떤 버그인가요?
일단 어제 풀리퀘 줬던 feature/friend 랑 feature/mycake-main 각 브랜치에 머지하고
두 브랜치를 main으로 머지하여 main에서 해당 기능들을 테스트 하는 도중이었음..

> 케이크 정보 열람시 모달창 여러번 나타나는 버그

## 어떤 상황에서 발생한 버그인가요?
로그인 한 후에 케이크 정보를 불러오는 모달창이 두번 열림.
<img width="446" alt="image" src="https://github.com/patisiel-study/decorate-my-cake-frontend/assets/84646738/8e9913d6-8d50-46a4-b381-0c0ec010275b">
여기서 확인누르면
<img width="485" alt="image" src="https://github.com/patisiel-study/decorate-my-cake-frontend/assets/84646738/15e6d3c2-f3b1-4e2d-881d-847d49e21a35">
또 나옴

그다음 확인 누르면 페이지를 불러오기는 하지만 반응형으로 안되어 있어서 창 크기 조절되면 이렇게 컴포넌트가 겹침.
<img width="1418" alt="image" src="https://github.com/patisiel-study/decorate-my-cake-frontend/assets/84646738/d44cb755-6f9a-4692-b732-a27727fda685">

오른쪽에 뜨는 
데이터를 가져오는 중 오류가 발생했습니다. TypeError: Cannot read properties of null (reading 'toString')
    at fetchData (MyCakeMain.jsx:36:1
에러는 내쪽에서 잘못된 것 같으니 확인해보겠음.

**Comment by Dinogarlic** [comment]
노션 링크: [https://www.notion.so/astar5327z/6ea3b3e883964e918fbc83029752d2b4?pvs=4]

React.StrictMode를 제거했을 때 API 호출이 한 번만 발생하는 것을 확인했다면, 문제의 원인은 StrictMode였습니다. 이는 개발 모드에서 컴포넌트의 잠재적인 문제를 감지하기 위해 React가 의도적으로 컴포넌트를 두 번 렌더링하기 때문입니다.

### 프로덕션 환경에서는 StrictMode 유지하기

StrictMode는 개발 모드에서만 활성화되므로, 실제 프로덕션 환경에서는 이 문제가 발생하지 않습니다. 따라서, 개발 시에는 StrictMode를 유지하여 코드의 잠재적인 문제를 사전에 발견하고 해결하는 것이 좋습니다.

### 해결 방안

1. **StrictMode 유지**: 개발 모드에서는 StrictMode를 유지하고, API 호출이 두 번 발생하는 것을 인지하고 작업합니다.
2. **API 호출 최적화**: API 호출이 두 번 발생해도 문제없이 작동하도록 코드를 작성하거나, 캐시를 활용하여 동일한 API 호출이 중복되지 않도록 할 수 있습니다.
